BUGFIX. Changes of the hostile commanded AI logic
ss220-space/Baystation12 pull request #188
Opened 2022-04-25 19:59 UTC by Zhuzhila

# Описание

Проведена работа над ИИ Рекса и других управляемых мобов.

## Основные изменения

* Правка открывания штор мобами
* Правка призыва моба-защитника в случае получения удара
* Управляемым мобам добавлена команда забыть цель
* Исправлен баг: моб слушается одновременно и мастер и "друзей"
* Рексу добавлена вариативность наносимых ударов

## Changelog

:cl:
bugfix: Правка открывания штор мобами
bugfix: Правка возможности кормить Рекса когда тот мертв
bugfix: Правка призыва моба-защитника в случае получения удара
bugfix: Исправлен баг: моб слушается одновременно и мастер и "друзей"
tweak: Рексу добавлена вариативность наносимых ударов
tweak: Управляемым мобам добавлена команда забыть цель: forget target {target_name}
/:cl:

2022-05-07 07:36 UTC, Vallat requested changes

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +	if(!(M.a_intent == I_HELP) && retribution) //assume he wants to hurt us.
```suggestion
	if(M.a_intent != I_HELP && retribution) //assume he wants to hurt us.
```

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +			return
```suggestion
			return TRUE
```

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +		return
```suggestion
		return TRUE
```

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +			return
```suggestion
			return TRUE
```

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +			visible_message("<span class='notice'>The [user] start feeding the [src] [O]")
Откатить обратно 
```suggestion
			visible_message(SPAN_NOTICE("\The [user] start feeding the [src] [O]"))
```

2022-05-07 07:36 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +				visible_message("<span class='notice'>The [src] ate [O]")
Откатить обратно 
```suggestion
				visible_message(SPAN_NOTICE("\The [src] ate [O]"))
```

2022-05-07 07:49 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +			dealt_damage = attack.damage <= dealt_damage ? dealt_damage : attack.damage
```suggestion
			dealt_damage = max(dealt_damage, attack.damage)
```

2022-05-07 07:52 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +/mob/living/simple_animal/hostile/commanded/rex/attack_hand(mob/living/carbon/human/M as mob)
```suggestion
/mob/living/simple_animal/hostile/commanded/rex/attack_hand(mob/living/carbon/human/target)		
```
Это же цель атаки, я правильно понимаю?

2022-05-07 07:52 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +/mob/living/simple_animal/hostile/commanded/rex/attack_hand(mob/living/carbon/human/M as mob)
as mob - имеет смысл только в verb, насколько я знаю

2022-05-07 09:55 UTC, Zhuzhila commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +/mob/living/simple_animal/hostile/commanded/rex/attack_hand(mob/living/carbon/human/M as mob)
скорее это моб которые воздействует на Рекса, не обязательно цель атаки

2022-05-07 15:33 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +/mob/living/simple_animal/hostile/commanded/rex/attack_hand(mob/living/carbon/human/M as mob)
ну тогда назови как надо

2022-05-08 09:04 UTC, Zhuzhila commented on code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
> +/mob/living/simple_animal/hostile/commanded/rex/attack_hand(mob/living/carbon/human/M as mob)
хм, забавно, мне казалось оно подтягивает и сюда изменения, ну короче изменил

2022-05-23 11:03 UTC, merged