rogue_drone weapon variability
ss220-space/Baystation12 pull request #189
Opened 2022-04-25 20:43 UTC by Zhuzhila

# Описание

реализация следующего предложения:
![image](https://user-images.githubusercontent.com/80123534/165171159-cb54a399-2459-4bf2-abd2-1de15fd3ac0d.png)

Предметы для оружия взяты из стандартного набора инструментов дрона

## Основные изменения

* Добавлена вариативность используемого оружия сбойными дронами

## Changelog

:cl:
tweak: Добавлена вариативность используемого оружия сбойными дронами
/:cl:

2022-04-26 07:21 UTC, Zhuzhila commented
пока не мержить, надо добавить правку что б предметы не выкладывались на стол

2022-05-03 19:16 UTC, Zhuzhila commented
Поправил возможность дрона складывать вещи на стол, возможно есть более правильное решение, если укажут будет хорошо, а пока могу придумать только так

2022-05-03 21:50 UTC, Zhuzhila commented
добавил легкий взрыв на тайле с мобом и вспышку в два тайла радиусом

2022-05-05 17:46 UTC, Gaxeer approved these changes

2022-05-05 17:46 UTC, Vallat requested changes

2022-05-05 17:46 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/bad_drone.dm
> +	. = ..()
Взрыв может вызвать повторную смерть, для начала лучше вызвать код родителя
```suggestion
	. = ..()
	explosion(src.loc, 0, 0, 1, 3, 0)
```

2022-05-05 17:46 UTC, Vallat commented on code/modules/mob/living/simple_animal/hostile/bad_drone.dm
> +	QDEL_NULL(natural_weapon)
```suggestion
	if(natural_weapon)
		QDEL_NULL(natural_weapon)
```

2022-05-05 17:51 UTC, Zhuzhila commented on code/modules/mob/living/simple_animal/hostile/bad_drone.dm
> +	QDEL_NULL(natural_weapon)
#define QDEL_NULL(x) if(x) { qdel(x) ; x = null }
Зачем проверять дважды?

2022-05-05 17:53 UTC, Zhuzhila commented
Предложка не прошла, закрываю ПР

2022-05-05 17:53 UTC, closed without merging

2023-02-11 19:21 UTC, cuddleandtea commented on code/modules/mob/living/simple_animal/hostile/bad_drone.dm
> +	. = ..()
Спасибо за ревью! Неожиданно)