Xenobio update. More new stuff and fix for old
ss220-space/Baystation12 pull request #213
Opened 2022-05-18 14:37 UTC by Astolaf

# Описание
Дополнение к ксенобиологии. 
Ксенобиология нуждается в некоторой доработке. Сейчас она весьма мало используется. Как первая часть решения идет дополнение реакций. 

## Основные изменения
- Серый слайм и вода: 10 адреналина.
- Металлический слайм плюс вода дает теперь еще 5 укреп стекла.
- Золотой слайм плюс кровь спавнит враждебное существо.
- Серебряный слайм плюс вода дает случайный напиток.
- Блюспейс слайм плюс кровь дает 5  блюспейс кристаллов
- Оранжевый слайм плюс вода: дымовая граната, которая разносит содержимое ядра 
- Пиритовый слайм плюс вода даст красящие мелки 

- Баф слаймо батарейки. Емксоть 2500 и рабочий подзаряд.

## Changelog
:cl:
tweak: metal slime gives 5 reinforced glass
rscadd: added slime adrenalin
rscadd: added slime random drink
rscadd: added slime crayons 
rscadd: added slime bluespace crystals  
rscadd: added slime hostile mobs 
experiment: smoke grenade from slime 
balance: rebalanced slime cell
/:cl:

2022-05-19 20:53 UTC, Gaxeer requested changes

2022-05-19 20:53 UTC, Gaxeer commented on code/modules/reagents/Chemistry-Recipes.dm
> +		S.start()
```suggestion
	var/datum/effect/effect/system/smoke_spread/chem/smoke_effect = new
	smoke_effect.attach(location)
	smoke_effect.set_up(holder, 8, 0, location)
	playsound(location, 'sound/effects/smoke.ogg', 50, 1, -3)
	INVOKE_ASYNC(smoke_effect, /datum/effect/effect/system.proc/start)
```

2022-05-19 20:53 UTC, Gaxeer commented on code/modules/reagents/Chemistry-Recipes.dm
> +			M.flash_eyes()
```suggestion
	for(var/mob/living/carbon/human/viewer in viewers(get_turf(holder.my_atom), null))
		if(viewer.eyecheck() < FLASH_PROTECTION_MODERATE)
			viewer.flash_eyes()
```

2022-05-19 20:53 UTC, Gaxeer commented on code/modules/reagents/Chemistry-Recipes.dm
> +
```suggestion
		var/obj/bork_drink = new chosen(get_turf(holder.my_atom))
		if(!bork_drink)
			continue
			
		if(prob(50))
			for(var/j in 1 to rand(1,3))
				step(bork_drink, pick(NORTH, SOUTH, EAST, WEST))
```

2022-05-19 20:53 UTC, Gaxeer commented on code/modules/reagents/Chemistry-Recipes.dm
> +	for(var/i = 1, i <= 3, i++)
```suggestion
	for(var/i in 1 to 3)
```

2022-05-19 20:53 UTC, Gaxeer commented on code/modules/reagents/Chemistry-Recipes.dm
> +	for(var/i = 1, i <= 4 + rand(1,2), i++)
```suggestion
	for(var/i in 1 to (4 + rand(1,2)))
```

2022-05-20 08:32 UTC, Zhuzhila commented
Предложения по эффекту на кровь псионика:
- зеленый - у псиоников единоразово повышает уровень пси-развития
- серебряный - спавнит рандомные блюда куда добавляется триглаз
- желтый - пси-крик который вырубает на пару секунд всех органиков не являющимися активными псиониками (т.е. латента рубит так же)
- красный - всем органикам пишется про то как они хотят избить соседа, что они дико хотят избить соседа, что они "ПРЯМ ПИСЕЦ КАК ХОТИТЕ ВСТУПИТЬ В ДРАКУ ГОЛЫМИ РУКАМИ!!!!!", а у всех симплмобов вызывает бешенство
- черный - микстура дающая пси-силы НЕ псионикам
- светло-розовый - зелье использовав которое на органике делает из него вашего веного друга(аналог импланта подчинения)
- пурпурный - в атмосферу выпрыскивается приличное число химикатов/генов (прикол чисто для генок)
- лазурный - зелье повышающее объем крови органика в 1.5 раза
- блюспейс - вколовшему дается навык мага на создание порталов

2022-05-21 18:20 UTC, Astolaf commented
Правки по коду сделаны.
Можно сливать

2022-05-22 14:34 UTC, Gaxeer approved these changes

2022-05-23 11:04 UTC, merged