Fix: hookah
ss220-space/Baystation12 pull request #222
Opened 2022-05-27 18:59 UTC by HaCsO

Починил кальян который кодил когда был ебаглаком. В будущем планирую дорабатывать как нибудь, наверное...

2022-05-27 19:07 UTC, Vallat requested changes

2022-05-27 19:07 UTC, Vallat commented on infinity/code/game/objects/items/hookah.dm
> +	if(reagents.reagent_list.len > 0)
```suggestion
	if(length(reagents.reagent_list) > 0)
```

2022-05-27 19:07 UTC, Vallat commented on infinity/code/game/objects/items/hookah.dm
> +			return
```suggestion
		if(!coals)
			return
```

2022-05-27 19:07 UTC, Vallat commented on infinity/code/game/objects/items/hookah.dm
> +			qdel(box.contents[1])
```suggestion
		for(var/i in 1 to coals)
			qdel(box.contents[1])
```

2022-05-27 19:07 UTC, Vallat commented on infinity/code/game/objects/items/hookah.dm
> +		qdel(T)
```suggestion
	for(var/obj/item/tube/T as anything in tubes_archive)
		qdel(T)
```

2022-05-27 19:07 UTC, Vallat commented on infinity/code/game/objects/items/hookah.dm
> +				for(var/obj/item/tube/T in tubes_archive)
```suggestion
				for(var/obj/item/tube/T as anything in tubes_archive)
```

2022-05-27 20:27 UTC, Gaxeer requested changes

2022-05-27 20:27 UTC, Gaxeer commented on infinity/code/game/objects/items/hookah.dm
> +	if(parent.reagents && parent.reagents.total_volume) // check if it has any reagents at all
```suggestion
	if(parent.reagents?.total_volume) // check if it has any reagents at all
```

2022-05-27 20:27 UTC, Gaxeer commented on infinity/code/game/objects/items/hookah.dm
> +/obj/item/tube/proc/check_exited(var/mob/mover)
Ты обьявляешь proc, принимаешь moverа, но не используешь его

2022-05-27 20:32 UTC, Gaxeer commented on infinity/code/game/objects/items/hookah.dm
>  /obj/item/hookah/New()
Замени New() на Initialize()

2022-05-28 05:50 UTC, Vallat approved these changes

2022-05-28 06:16 UTC, Gaxeer commented
ну калямбецал двойным яблочком забить надо по такому случаю

2022-05-28 06:16 UTC, Gaxeer approved these changes

2022-05-29 15:53 UTC, merged