Lord of the Lockers [animation port from /tgstation] [MDB IGNORE]
ss220-space/Baystation12 pull request #267
Opened 2022-07-05 06:44 UTC by ImJustKisik

Описание: 
Перенос анимации работы шкафчиков с Yogstation
Перенос анимации ящиков с TG/Station
Перенос анимации гроба из моей головы
Респрайт ящиков и шкафов
Добавлены новые звуки для гроба, ящиков и деревянного шкафа
Добавлены новые спрайты для настенных шкафчиков
Добавлена анимация для настенных ящиков

🆑
rscadd: "Перенос анимации ящиков с /tg."
soundadd: "Добавлены новые звуки открывания шкафов и ящиков."
imageadd: "Респрайт ящиков под 3/4."
rscadd: "Анимация открытия ящиков и бодибагов."
refactor: "Небольшой рефактор кода ящиков."
/🆑

2022-07-06 21:51 UTC, Astolaf commented
в карго на складе нет спрайтов у ящиков у стенки

2022-07-06 21:53 UTC, ImJustKisik commented
@Astolaf 
![image](https://user-images.githubusercontent.com/87862013/177649959-39f6759f-ddcd-4487-b001-6bb0154a151e.png)
Вот так нет, или вообще нет?

2022-07-07 07:33 UTC, Vallat requested changes

2022-07-07 07:33 UTC, Vallat commented on code/game/objects/structures/crates_lockers/crates.dm
> +	for(var/I in 0 to num_steps)
`I` - Image, `i` - iterator. Рекомендую сменить название переменной хотя бы на `i`, в идеале, конечно, это должен быть `step`

2022-07-07 07:33 UTC, Vallat commented on code/game/objects/structures/crates_lockers/crates.dm
> +	for(var/I in 1 to num_steps_1) //loop to save the animation values into the lists
`I` - Image, `i` - iterator. Рекомендую сменить название переменной хотя бы на `i`, в идеале, конечно, это должен быть `step`

2022-07-07 07:33 UTC, Vallat commented on code/game/objects/structures/crates_lockers/closets/__closet.dm
> +	for(var/I in 0 to num_steps)
`I` - Image, `i` - iterator. Рекомендую сменить название переменной хотя бы на `i`, в идеале, конечно, это должен быть `step`

2022-07-07 07:33 UTC, Vallat commented on code/game/objects/structures/crates_lockers/closets/__closet.dm
> +	for(var/I in 0 to num_steps)
`I` - Image, `i` - iterator. Рекомендую сменить название переменной хотя бы на `i`, в идеале, конечно, это должен быть `step`

2022-07-07 13:06 UTC, Astolaf commented
> @Astolaf ![image](https://user-images.githubusercontent.com/87862013/177649959-39f6759f-ddcd-4487-b001-6bb0154a151e.png) Вот так нет, или вообще нет?

Серых не было. Также я бы обратил внимание на настенный шкаф в РнД у деструктора.

2022-07-09 06:59 UTC, Vallat approved these changes

2022-07-10 17:01 UTC, ImJustKisik commented
!review

2022-07-15 14:29 UTC, merged

2022-07-15 15:11 UTC, Bizzonium commented
Игроки недовольны стилем иконок