Port of ship traits
ss220-space/Baystation12 pull request #313
Opened 2022-08-04 13:32 UTC by ImJustKisik

# Описание

Частично является переносом #tgstation/tgstation/pull/56309
Делает каждый новый раунд несколько отличным от предыдущего, потенциально делая его легче/труднее/

# Текущие особенности 

*** Позитивные** 

- Грант на исследование - Карго будет начинать с 100 поинтов вместо 50
- Быстрая доставка - Шатлл карго будет лететь меньше времени.
- Премиальные ящики выживания - Survaival crew boxes будут иметь дополнительное оборудование. (autoinjector (painkiller) и advanced trauma kit)

***Нейтральные**

- Неестественная атмосфера - На экзопланетах будет больше вероятности наличия опасных/неестественных газов.

***Негативные**

- Медленная доставка - Шатлл карго будет лететь больше времени.
- Перегрузка освещения - Некоторые АПЦ на корабле будут запускаться с отключенным освещением.
- Штраф за перевозку грузов  - Карго будет начинать с 25 поинтов вместо 50

2022-08-04 13:35 UTC, ImJustKisik commented
![image](https://user-images.githubusercontent.com/87862013/182860309-b87b0dfa-f754-426a-afdf-e3d3433243c7.png)

2022-08-05 10:39 UTC, PhantornRU commented on code/datums/station_traits/positive.dm
> +	report_message = "В связи с изменением цен на товары, стоимость заказов пересмотрена - свертесь с прайсом"
```suggestion
	report_message = "В связи с изменением цен на товары, стоимость заказов пересмотрена - сверьтесь с прайсом"
```

2022-08-05 10:40 UTC, PhantornRU commented on code/datums/station_traits/negative.dm
> +	report_message = "В связи с изменением цен на товары, стоимость заказов пересмотрена - свертесь с прайсом"
```suggestion
	report_message = "В связи с изменением цен на товары, стоимость заказов пересмотрена - сверьтесь с прайсом"
```

2022-08-05 10:41 UTC, PhantornRU commented on code/datums/station_traits/positive.dm
> +	report_message = "Crew survival boxes оснащены дополнительным оборудованием."
```suggestion
	report_message = "Crew survival boxes оснащенные дополнительным оборудованием."
```

2022-08-05 10:43 UTC, PhantornRU commented on code/datums/station_traits/positive.dm
> +	report_message = "Благодаря близости к нашей ближайшей станции снабжения, ваш шаттл снабжения будет иметь более быстрое время доставки."
Близости к ближайшей...
```suggestion
	report_message = "Близкое расположение нашей станции снабжения, позволяет быстрее доставлять грузы на шаттле."
```

2022-08-05 10:44 UTC, PhantornRU commented on code/datums/station_traits/neutral.dm
> +	report_message = "Планеты в вашей системе могут иметь более необычные атмосферные характеристики."
```suggestion
	report_message = "Планеты вашей системы обладают необычными атмосферными характеристиками."
```

2022-08-05 10:45 UTC, PhantornRU commented on code/datums/station_traits/negative.dm
> +	report_message = "Из-за расстояния до станции снабжения, шаттл снабжения будет иметь большую длительность доставки до вашего местоположения."
```suggestion
	report_message = "Из-за отдаленности до станции снабжения, доставка грузов на шаттле замедленна."
```

2022-08-05 10:45 UTC, PhantornRU commented on maps/sierra/sierra_setup.dm
> +			welcome_text += "<hr><b>Выявленные нештатные ситуации в смене:</b><BR>"
```suggestion
			welcome_text += "<hr><b>Выявленные нештатные ситуации на смене:</b><BR>"
```

2022-08-05 10:46 UTC, PhantornRU requested changes
Основной код глянул, особо проблем не заметил, возможно не хватает опыта. Но заметил недочеты в переводе. Поверхностно поправил.

2022-08-05 16:14 UTC, PhantornRU approved these changes

2022-08-06 11:29 UTC, Vallat approved these changes

2022-08-07 17:17 UTC, closed without merging