Sprite abyss
ss220-space/Baystation12 pull request #357
Opened 2022-09-10 23:08 UTC by Astolaf

# Описание
Новые спрайты

## Основные изменения
Допишу позже 

## Changelog

:cl:
rscadd: added new things
imageadd: added some icons and images
/:cl:

2022-09-11 16:07 UTC, Bizzonium requested changes

2022-09-11 16:07 UTC, Bizzonium commented on code/modules/clothing/under/accessories/badges.dm
> +	slot_flags = SLOT_TIE | SLOT_BELT
```suggestion
	slot_flags = SLOT_TIE | SLOT_BELT

```

2022-09-11 16:07 UTC, Bizzonium commented on code/modules/clothing/under/accessories/badges.dm
>  	icon_state = "badge_round"
```suggestion
	icon_state = "badge_round"

```

2022-09-11 16:07 UTC, Bizzonium commented on code/modules/clothing/under/accessories/badges.dm
> +	badge_string = null
```suggestion
	badge_string = null

```

2022-09-11 16:07 UTC, Bizzonium commented on code/modules/clothing/under/accessories/badges.dm
> +	badge_string = null
```suggestion
	badge_string = null

```

2022-09-11 16:07 UTC, Bizzonium commented on code/modules/clothing/under/accessories/badges.dm
> +	w_class = ITEM_SIZE_TINY
```suggestion
	w_class = ITEM_SIZE_TINY

```

2022-09-11 16:08 UTC, merged

2022-09-29 12:15 UTC, ImJustKisik commented on code/game/machinery/atmoalter/canister.dm
>  		overlays += "can-o2"
overlays += overlay_image(icon, "can-o2", plane = EFFECTS_ABOVE_LIGHTING_PLANE, layer = ABOVE_LIGHTING_LAYER)

2022-09-29 12:15 UTC, ImJustKisik commented on code/game/machinery/atmoalter/canister.dm
>  		overlays += "can-o3"
overlays += overlay_image(icon, "can-o3", plane = EFFECTS_ABOVE_LIGHTING_PLANE, layer = ABOVE_LIGHTING_LAYER)