Feat: Интегралки на мехи
ss220-space/Baystation12 pull request #47
Opened 2021-07-11 21:04 UTC by Predeiter

## Changelog
:cl:
Feat: Добавлена сборка - тип "exo" (large size type), добавлено новое оборудование на мехи - держатель интегральных сборок.
/:cl:

2021-07-11 23:23 UTC, keIgaras commented
Чувствую я грядут мехи на крови резоми

2021-07-12 05:59 UTC, Vallat requested changes
В целом нормально, поменять то, что я отметил

2021-07-12 05:59 UTC, Vallat commented on code/modules/mechs/equipment/utility.dm
> +	..()
Зачем это вообще нужно, если оно вызывает родителя?

2021-07-12 05:59 UTC, Vallat commented on code/modules/mechs/equipment/utility.dm
> +/obj/item/mech_equipment/mounted_system/circuit/attackby(obj/item/W as obj, mob/user as mob)
```suggestion
/obj/item/mech_equipment/mounted_system/circuit/attackby(obj/item/W, mob/user)
```
**as obj** и **as mob** в данном случае не несут никакого логического эффекта

2021-07-12 05:59 UTC, Vallat commented on code/modules/mechs/equipment/utility.dm
> +	if(istype(W, /obj/item/device/electronic_assembly/large/exo_frame))
```suggestion
	else if(istype(W, /obj/item/device/electronic_assembly/large/exo_frame))
```
И убрать **return** из каждого условного блока

2021-07-12 11:56 UTC, quardbreak requested changes

2021-07-12 11:56 UTC, quardbreak commented on code/modules/mechs/equipment/utility.dm
> +	desc = "A DIY circuit rack for exosuit. Circuitry not included"
Точку забыл в конце предложения.

2021-07-12 11:56 UTC, quardbreak commented on code/modules/mechs/equipment/utility.dm
> +	name = "Exo circuit rack"
Названия предметов в игре в большинстве случаев начинается с маленькой буквы.
Предлагаю переименовать в `exosuit circuit rack` чтобы было лучше понятно, а то `exo` не оч.

2021-07-12 12:07 UTC, Bizzonium commented on code/modules/mechs/equipment/utility.dm
> +	name = "Exo circuit rack"
@quardbreak а как тебе по балансу эта фича?

2021-07-12 12:16 UTC, quardbreak commented on code/modules/mechs/equipment/utility.dm
> +	name = "Exo circuit rack"
Я положительно отношусь к любым фичам относительно мехов или интегралок, правда, на бэе интегралки немного устарели и имеют немного странные механики в контексте баланса.
Мне сказали, что пока мехи могут брать самые большие интегралки, поэтому лучше бы ограничить до какого-то размера.

2021-07-12 16:59 UTC, Predeiter commented on code/modules/mechs/equipment/utility.dm
> +	name = "Exo circuit rack"
> Названия предметов в игре в большинстве случаев начинается с маленькой буквы.
> Предлагаю переименовать в `exosuit circuit rack` чтобы было лучше понятно, а то `exo` не оч.

@quardbreak Изначально название было просто заглушкой, поменял на предложенный вариант.

2021-07-12 17:21 UTC, Predeiter commented on code/modules/mechs/equipment/utility.dm
> +	name = "Exo circuit rack"
@quardbreak Пока с размером сборки не решил, так как для изменения размера нужно будет прописывать новую группу с другим множителем макроса отвечающего за размер сборок.

2021-07-15 06:46 UTC, Vallat approved these changes

2021-09-10 14:31 UTC, merged