DF posters
ss220-space/Baystation12 pull request #491
Opened 2023-02-05 10:22 UTC by cuddleandtea

# Добавление трёх новых постеров в игру

* Постеры по тематике dwarf fortress 

## Скриншоты

| Картинка                  | Описание|
| ---------------------- | ---------------------- |
| ![image](https://user-images.githubusercontent.com/105150564/216813484-d1ae4205-f8b5-4523-a190-e476849f8560.png) | На постере вы видите множество шаттлов и кораблей летящих в неизвестность космоса. "В поисках ресурсов множество кораблей и шаттлов отправляются в разные уголки галактики, и шахтеры на них сами куют свою судьбу, ведь она в их руках!". Маленькая бирка внизу указывает на то, что этот постер проспонсирован Grayson Manufactories - HRM | 
| ![image](https://user-images.githubusercontent.com/105150564/216813489-f71ba13a-55b1-469a-aab2-bee4eb266524.png) | На данном постере можно увидеть бородатого человека, с кружечкой пенного. "После смены на шахте, всегда стоит зайти в бар и освежиться кружкой холодного пива. Ведь никто не будет осуждать вас за протирание штанов и танцы на пьяную голову". Бирка внизу постера указывает на то, что постер проспонсирован Grayson Manufactories - HRM |
| ![image](https://user-images.githubusercontent.com/105150564/216813497-a009b27f-5fe7-4873-82ee-3bbe1abbd90c.png) | Постер, на котором нарисован персонаж из старых времен, имени его никто не помнит, но обычно про него говорят в хорошем тоне |

2023-02-05 14:36 UTC, SuhEugene requested changes
Из-за нового подтипа `/nyc/`, который я создал по дурости, иногда появляется пустой постер: без имени, описания и картинки.

Решение с рандомизацией корня, думаю, выглядело бы костыльным, потому я в ПР #481 это пофиксил переименованием `/nyc/postername` в `/nyc_postername`.

Чтоб этот баг не появился вновь, нужно это повторить и здесь.

2023-02-05 14:36 UTC, SuhEugene commented on infinity/code/game/objects/effects/decals/posters.dm
> +/decl/poster/nyc/forge
```suggestion
/decl/poster/nyc_forge
```

2023-02-05 14:36 UTC, SuhEugene commented on infinity/code/game/objects/effects/decals/posters.dm
> +/decl/poster/nyc/space_dwarf
```suggestion
/decl/poster/nyc_space_dwarf
```

2023-02-05 14:36 UTC, SuhEugene commented on infinity/code/game/objects/effects/decals/posters.dm
> +/decl/poster/nyc/good_old_times
```suggestion
/decl/poster/nyc_good_old_times
```

2023-02-07 18:00 UTC, AlexMorgan3817 commented on infinity/code/game/objects/effects/decals/posters.dm
> +	// by Скавен-крыс
Выглядит как копипаст копирайта из префаба чуть выше 🐸

2023-03-08 14:56 UTC, merged